SUPABASE_URL = "https://wfkrxunidqliuehgowyh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indma3J4dW5pZHFsaXVlaGdvd3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzYzMDYsImV4cCI6MjA2NzcxMjMwNn0.tl1SJGC3qoWRzkylBqhAS2zuDenJoMYGRVqPaRITnkA"
